"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Permission = exports.UserRole = void 0;
var UserRole;
(function (UserRole) {
    UserRole["SUPER_ADMIN"] = "super_admin";
    UserRole["SCHOOL_ADMIN"] = "school_admin";
    UserRole["TEACHER"] = "teacher";
    UserRole["PARENT"] = "parent";
    UserRole["STUDENT"] = "student";
})(UserRole || (exports.UserRole = UserRole = {}));
var Permission;
(function (Permission) {
    Permission["MANAGE_ALL_SCHOOLS"] = "manage_all_schools";
    Permission["APPROVE_SCHOOLS"] = "approve_schools";
    Permission["SUSPEND_SCHOOLS"] = "suspend_schools";
    Permission["MANAGE_SUBSCRIPTIONS"] = "manage_subscriptions";
    Permission["VIEW_SYSTEM_ANALYTICS"] = "view_system_analytics";
    Permission["MANAGE_SCHOOL_PROFILE"] = "manage_school_profile";
    Permission["MANAGE_CLASSES"] = "manage_classes";
    Permission["MANAGE_SECTIONS"] = "manage_sections";
    Permission["MANAGE_SUBJECTS"] = "manage_subjects";
    Permission["MANAGE_STUDENTS"] = "manage_students";
    Permission["MANAGE_TEACHERS"] = "manage_teachers";
    Permission["MANAGE_STAFF"] = "manage_staff";
    Permission["VIEW_ATTENDANCE"] = "view_attendance";
    Permission["MANAGE_EXAMS"] = "manage_exams";
    Permission["MANAGE_RESULTS"] = "manage_results";
    Permission["MANAGE_FEES"] = "manage_fees";
    Permission["SEND_NOTICES"] = "send_notices";
    Permission["TAKE_ATTENDANCE"] = "take_attendance";
    Permission["UPLOAD_HOMEWORK"] = "upload_homework";
    Permission["UPLOAD_MATERIALS"] = "upload_materials";
    Permission["ENTER_EXAM_MARKS"] = "enter_exam_marks";
    Permission["SEND_CLASS_NOTICES"] = "send_class_notices";
    Permission["COMMUNICATE_PARENTS"] = "communicate_parents";
    Permission["VIEW_ASSIGNED_CLASSES"] = "view_assigned_classes";
    Permission["VIEW_STUDENT_DATA"] = "view_student_data";
    Permission["VIEW_CHILD_ATTENDANCE"] = "view_child_attendance";
    Permission["VIEW_HOMEWORK"] = "view_homework";
    Permission["VIEW_NOTICES"] = "view_notices";
    Permission["VIEW_EXAM_RESULTS"] = "view_exam_results";
    Permission["VIEW_PERFORMANCE"] = "view_performance";
    Permission["VIEW_FEES"] = "view_fees";
    Permission["COMMUNICATE_TEACHERS"] = "communicate_teachers";
    Permission["VIEW_OWN_HOMEWORK"] = "view_own_homework";
    Permission["VIEW_OWN_RESULTS"] = "view_own_results";
    Permission["VIEW_CLASS_ROUTINE"] = "view_class_routine";
    Permission["VIEW_OWN_NOTICES"] = "view_own_notices";
})(Permission || (exports.Permission = Permission = {}));
//# sourceMappingURL=roles.enum.js.map